# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d810e9b51bed93479cb9d28a3b2fc8f8185728be5aa48b59d3b37745449b2ad111b1e11983a3878393fd6dff248778c17b37beb6bf948aede55cdb8ecded0ec7

test:
  secret_key_base: 62acd3fb9d1c34273271309fa679999c07dfcee164f8d57d6fce7ca04d2c66bd49c29718285f28abc34a3a26ce278ecb7b33270693a81f3c9ec04059a8bdfa30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
